name: Test and Tag

on:
  push:
    branches:
      - main
      - cross-platform-tests

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml

  check-for-and-create-new-release:
    name: Create new release tag if needed
    runs-on: ubuntu-latest
    needs:
      - test

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - shell: bash
        run: |
          VERSION=$(yq -oy '.package.version' Cargo.toml)
          if git tag --list | grep "^$VERSION\$" >>/dev/null 2>&1; then
            echo "Version $VERSION already tagged, no release to complete"
            exit 0
          fi

          echo "Continuing to create release tag"

          git config user.name BridgeBoard-PC-Boot-Patcher-AutoRelease

          git tag "$VERSION"
          git push origin "$VERSION"
