# Thanks to https://dzfrias.dev/blog/deploy-rust-cross-platform-github-actions on which
# most of this workflow was based
name: Run Tests

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: cargo test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - build: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows-gnu-x86_64
            os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Run tests
        shell: bash
        run: |
          cargo test --target "${{ matrix.target }}" --all-features

